### ISSUE TITLE
Consider doing a refactor of package naming policy

### ISSUE THREAD

**Issue by thewilly** [weso/sutils#1]
Now packaging naming follows the following pattern: es.weso.<<MODULE_NAME>>, for example for module document the package declaration is `package es.weso.document`. That does not follow the naming conventions of Scala that state that _[should follow the Java package naming conventions](https://docs.scala-lang.org/style/naming-conventions.html#packages )_.

In order to fix that, the proposal is to change naming policy to es.weso.**sutils**.<<MODULE_NAME>>, that way the above example should be refactored to es.weso.sutils.document.

**Comment by labra** [comment]
Good point. 

This package was originally called `utils` instead of `sutils`. 

We changed the name to avoid collision with another component that was used in `srdf` but now that all these modules have been separated in a single package, it would make more sense to rename all of them back to `utils`.

**Comment by labra** [comment]
I have already moved all the code in this repository to [https://github.com/weso/utils](https://github.com/weso/utils).
